-- Granting SIG_DEPLOY role to sysadmin
GRANT ROLE SIG_DEPLOY TO ROLE SYSADMIN;

-- Granting creation of all account level objects and schema level objects privileges to SIG_DEPLOY
GRANT CREATE DATABASE ON ACCOUNT TO ROLE SIG_DEPLOY;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE SIG_DEPLOY;
GRANT CREATE ROLE ON ACCOUNT TO ROLE SIG_DEPLOY;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE SIG_DEPLOY;

-- Granting Required privileges to SIG_ELT
grant usage on database MOCK_PROJECT_DB to role SIG_ELT;
GRANT ALL PRIVILEGES ON SCHEMA RAW to role SIG_ELT;
GRANT ALL PRIVILEGES ON SCHEMA curated to role SIG_ELT;
GRANT ALL PRIVILEGES ON SCHEMA consumption to role SIG_ELT;
GRANT ALL PRIVILEGES ON SCHEMA dashboard to role SIG_ELT;

GRANT ALL ON ALL TABLES IN SCHEMA RAW TO ROLE SIG_ELT;
GRANT ALL ON ALL TABLES IN SCHEMA CURATED TO ROLE SIG_ELT;
GRANT ALL ON ALL TABLES IN SCHEMA CONSUMPTION TO ROLE SIG_ELT;
GRANT ALL ON FUTURE TABLES IN SCHEMA RAW TO ROLE SIG_ELT;

GRANT ALL ON ALL STAGES IN SCHEMA RAW TO ROLE SIG_ELT;
GRANT ALL ON ALL FILE FORMATS IN SCHEMA RAW TO ROLE SIG_ELT;
GRANT USAGE ON WAREHOUSE mock_project_warehouse TO ROLE SIG_ELT;
GRANT USAGE ON WAREHOUSE load_wh TO ROLE SIG_ELT;

-- Granting Required Previleges to SIG_DEVELOPER

GRANT USAGE ON DATABASE MOCK_PROJECT_DB TO ROLE SIG_DEVELOPER;
GRANT USAGE ON DATABASE SNOWFLAKE TO ROLE SIG_DEVELOPER;
GRANT USAGE ON WAREHOUSE ADHOC_WH TO ROLE SIG_DEVELOPER;
GRANT IMPORTED PRIVILEGES ON DATABASE snowflake TO ROLE SIG_DEVELOPER;

-- Granting Required Previleges to SIG_PII

GRANT USAGE ON DATABASE MOCK_PROJECT_DB TO ROLE SIG_PII;
GRANT USAGE ON WAREHOUSE MOCK_PROJECT_WAREHOUSE TO ROLE SIG_PII;
GRANT USAGE ON SCHEMA MOCK_PROJECT_DB.RAW TO ROLE SIG_PII;
GRANT SELECT ON ALL TABLES IN SCHEMA MOCK_PROJECT_DB.RAW TO ROLE SIG_PII;

-- Granting Required Priveleges for SIG_ANALYTICS role which is used by tableau dashboards 
GRANT USAGE ON DATABASE MOCK_PROJECT_DB TO ROLE SIG_ANALYTICS;
GRANT USAGE ON SCHEMA CONSUMPTION TO ROLE SIG_ANALYTICS;
GRANT USAGE ON WAREHOUSE ADHOC_WH TO ROLE SIG_ANALYTICS;
GRANT ALL ON ALL TABLES IN SCHEMA CONSUMPTION TO ROLE SIG_ANALYTICS;